POST http://localhost:3000/classes/messages/
content-type: application/json

{
	"username": "Marry Poppins",
	"roomname": "main",
  "text": "whats poppin? me!"
}

# POST http://localhost:3000/classes/users/
# content-type: application/json

# {
# 	"username": "Marry Poppins"
# }

# POST http://localhost:3000/classes/messages/
# content-type: application/json

# {
# 	"username": "cindy",
# 	"roomname": "lobby",
#   "body": "hows it goin\" anne?"
# }
